apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db-recover
  namespace: authentik # Assuming you'll deploy Authentik here
spec:
  instances: 3 # For high availability (one primary, two replicas)
  storage:
    size: 4Gi # Adjust size based on your needs
    storageClass: longhorn-rc-1 # Set up longhorn before!!

  # Bootstrap configuration for initial database setup
  bootstrap:
    recovery:
      volumeSnapshots:
        storage:
          name: authentik-db-20251016152445
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io

  # Optional: PostgreSQL configuration parameters
  postgresql:
    parameters:
      max_connections: "100"

  backup:
    # Volume snapshot backups
    volumeSnapshot:
      className: longhorn-snapshot-vsc # Longhorn


  # # Define a dedicated service for read-only traffic
  # replica:
  #   serviceTemplate:
  #     metadata:
  #       name: authentik-db-replicas-service
