#ENC[AES256_GCM,data:fsLPTIzPhdCvyuwbEGMkXDU8ZJg9rlbedZcKNdNcecKqvYtkoElEDnuSwJKyv1Tsn/pKa3AKJtuhs+Byd3Evopo/NhQ=,iv:+yekQ4nELjAywuh6tb1A3JE6S1KatyTXYGHWWKPMW5E=,tag:bz21D6m5Ee7tWaQ4l5Dwrw==,type:comment]
#ENC[AES256_GCM,data:EzI39qLr2fHZdvtWHdvIHqubOs+I9Gd/A8HQuf32OxwmUQ4p0PB48nTOPVP5QuDGTne3my2mwn5mhLRHdXmOmg==,iv:ccN2w5pMbLgcJVNnjgYSAsmxpyQIpfMVWH34N/BqjEM=,tag:ek5N3f7sU/q7Wjs+kVovTw==,type:comment]
namespaceOverride: ENC[AES256_GCM,data:lfuXh69TqPar,iv:SeK3ye92tZzYpHX90Demnq+BeBIT3RvDstsdzQ6259o=,tag:yIizCpXXgOyWPyGr9sqYbg==,type:str]
global:
    namespaceOverride: ENC[AES256_GCM,data:SQunIfWr4FmU,iv:W8+TBP/CuabbLIgT7WnVgXTQdB7NNGu2rHiImZWJVk0=,tag:rnhiU0dl1ccmhxg8dfo/Aw==,type:str]
authentik:
    namespace: ENC[AES256_GCM,data:uYqyxAa/7iYE,iv:3sXpSYlmzF0rHAqiDVZ5Sqpbg4Ej1Klfx3EetAmsBNw=,tag:JcITeJIy2wkFIKFSx1eG+A==,type:str]
    secret_key: ENC[AES256_GCM,data:KtHcfO0vYAZ22jkT8ZcvJEVs7fFoY/hQPXKJ4Q4PBazXiT3lu3F/umhKRhzZROC7x1NuI/LZr159lx8kNFfD2ipGxvIlb5BJkyCeJMTIXBg=,iv:+zxyW5zQHZlmxNSperPWgRKIL/taiDv16MGrWPQi7js=,tag:GEHVHzpyjz3tJyMt4Bm03Q==,type:str]
    postgresql:
        host: ENC[AES256_GCM,data:9ZM2ckhLnHxz780h3I5S,iv:/RBJoyejXCrcYRaOq/Ie8WvktPu2FTW0Jx4e0ks/AS0=,tag:o2+qJPssIwB60c+XX/AQWQ==,type:str]
        user: ENC[AES256_GCM,data:3AhkFAKe1lr7mjQjMpCztTf9pyJMqnfzjN4Fk0lFZQ==,iv:oIS2Hl4DvMmsPLH1iizlN5j7/CfjWp7VdwT2SIIlWsY=,tag:ODjQAT+Ah74smCuBBhYi5g==,type:str]
        password: ENC[AES256_GCM,data:/liO/N5ZY9WD2cmYHmUEQB2JuIAkC9MvVb66Jh9oLg==,iv:5s8c0TvJaqKX8Dwfr3p3QiUEtLKK0SkEZ5kNZmgZ4jg=,tag:OaM4M98bLg0653vYNBJP9A==,type:str]
server:
    ingress:
        ingressClassName: ENC[AES256_GCM,data:VzXBod6SWA==,iv:8TV6960WhcJE9EoaQfHDtGnM70NM3cp+KTxoj1eJ0zs=,tag:DY7Ge8ggMIOI1UltujLBuw==,type:str]
        enabled: ENC[AES256_GCM,data:ZXOW1w==,iv:iVBuK9tkX7ml433n7M+XuqUNBDWZMIA7lFU3QS4M7kk=,tag:s0hpktL7vWUea6QlKp++cw==,type:bool]
        tls:
            - hosts:
                - ENC[AES256_GCM,data:cZKS2HxRwbOqbYSqUId2HRpLASdMtxWfqbo=,iv:BYCuCantvS/wd9sii2tmO+eU02YfpCX6ZCb9U7BbtA8=,tag:ZHOztvrQ09kORsrEtOHlig==,type:str]
        hosts:
            - ENC[AES256_GCM,data:dmMirr+2GYLM9wkOrQx0hrN3WV8yw7wDNHo=,iv:x6v2jxwhwB8zBGRrPn942gQ8DgXkX7Uq8HnfmUC+dSE=,tag:DSMtEiMnsuoD+ssYYSF7+Q==,type:str]
    volumes:
        - name: ENC[AES256_GCM,data:aYJwMcmxSXpOaNmjcGk=,iv:R8k7rywK761fe+6ymPgVM9g+mj03ZlRy5moLtJkmwPs=,tag:U+EDXLTjFdrpINMBViYUUQ==,type:str]
          secret:
            secretName: ENC[AES256_GCM,data:uluPA3YB3qIoemsGe0ck5A==,iv:mAem+CwcRfI087mLRVEqq1cqNiVncwcZSp/NkcJ9ZcE=,tag:CVmMaFavBmHYycGJih/o3Q==,type:str]
    volumeMounts:
        - name: ENC[AES256_GCM,data:IDx5MVV8T02krlXay14=,iv:SopkHIx1rhhmxGbUI+7c1K0WCn/pkxKBfGO6c9MVRyA=,tag:brayNvv3DMuQ9QiKLuVJQg==,type:str]
          mountPath: ENC[AES256_GCM,data:ybJqwenhcaO0NFcPoHix,iv:JMi/9+aCvqZZWfTkGDqHHxw764ftqBO/OBflKb2NY48=,tag:q1j7OQKOeY7yoKsPsE9Ggw==,type:str]
          readOnly: ENC[AES256_GCM,data:M8eztQ==,iv:CzOUu/7r4fdrNm2uzJVb1cbwP1SDEEZEK9WqCD4DZw8=,tag:Sawge9WkBknrKSdkbZpE0g==,type:bool]
worker:
    volumes:
        - name: ENC[AES256_GCM,data:oq/PWQ3CdR+VlEanhDc=,iv:5MvoEj2vaenJNbPp9EoSe7c4rjeXk8XFdDhVB9BaZRk=,tag:0Rk/uyjSLLzTkDt2fRk+8g==,type:str]
          secret:
            secretName: ENC[AES256_GCM,data:Omw9m/9N1wBwsus0RAU0Fw==,iv:KsAu2oaOxifEjfBoO5wOI3Ga5RvVrouaL9SSdk8F1/I=,tag:HMlQTIqVbsaMoFx3EKDQwA==,type:str]
    volumeMounts:
        - name: ENC[AES256_GCM,data:Wz67n9F/zTLKbjvUIwQ=,iv:Qja2i+f4i11a9BmZ4YbXb/CoA8b4Cs74j22/7FuC0Qg=,tag:nL1CmWJum9UWrW9GJ5xCWg==,type:str]
          mountPath: ENC[AES256_GCM,data:5PfuybfZAkLKxeyU5BAw,iv:rVEUpqxXi2/V4J8JO27xRzC12Tx226r3PnNtSws+Qwo=,tag:mEsMDDaOMdn48gNwI3BavA==,type:str]
          readOnly: ENC[AES256_GCM,data:ITuIRw==,iv:iLgmim4FbDIrHzThi3aRvlSgpD5AfChA8L4AVu5KPY8=,tag:yGbfmxWIJU5s+MBjCoc97g==,type:bool]
redis:
    enabled: ENC[AES256_GCM,data:oDkT8g==,iv:Jl2z6SgImBrw3P/AgXSXIlPVsqEqx3OXNoQFXJxGXI0=,tag:k9Hn5zK3J81aEebwuDOLqQ==,type:bool]
    #ENC[AES256_GCM,data:k2uT8EphTQw=,iv:0n8qkAiAbAsVIkfgHZ8+KsR+HoI4e7dYTHh4lH/de5U=,tag:1wlf2VFFl4UV8D5TvKEc9Q==,type:comment]
    #ENC[AES256_GCM,data:NqUIZL2c4kxNm+TAWcZK,iv:FfpTfWrFiN0Ou3QIYpeVm2acpSovAwRqj13Mtd3DPYQ=,tag:6a7VYJ82Gn2BQFBK9HQ3Pg==,type:comment]
    #ENC[AES256_GCM,data:nidSmFwBeEsmC/7s,iv:wpiLk0hAIQ2w6+IN72EAyAj9dpq8tv6vT1jIEJU/EX4=,tag:6um4L2fx3ZRifG/OV9S+Ow==,type:comment]
sops:
    age:
        - recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcldMY1F4MllTSUhEMUdU
            SUtYRW84aU9FeDZ0NkZVbmV6djVYYmxQOFN3CnRaNXVZeDRaRVYwbHBaRGV5RTA0
            WjNUQWdpdHlvU2x4cFMyOWt3THpFQVkKLS0tIFhjU3U2VHcwWVNkcFRXYmJ1dEtV
            NndLZXJiTjlBdHpoQ2laQWROakdiMVUK3yCrMfm37MLVTz2RH7hsmnZme/SlI7+S
            CAhAKra+KSLrQXmlcQf+I8t2Y0HXfkKILSwY+z1g4xy+YIbMz+a8yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-11T19:23:49Z"
    mac: ENC[AES256_GCM,data:dtgbc7lwzJIkmSHju3iAls5mUHiLaB+olbvjE5IwjnardMmzed6o8zhUosrUhE/0idUK5BiqtKJrBNuQAVZKBv+6Uuh5lJU4geLNORt15rj/2WciIXSDnH5ABhVpzvk1wE5x7QCrM5UP4aeD8r4sBxcno9FJwftW01+q1LVxsz0=,iv:L0XyRqMp/Tujq7T7wqL0WW4JpdrMtYuKnq6yQp8aCw4=,tag:G71jenHKzFF5jtlG+T1YiA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
