apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    showNodeData: true

  settings.yaml: |
    title: Tyron's Home Lab
    background: https://github.com/orangci/walls-catppuccin-mocha/blob/7bfdf10d16ad3a689f9f0cf3a0930da3d1a245a8/waterfall.png?raw=true
    cardBlur: sm
    theme: dark
    base: https://home.tyrongabriel.com
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
      provider: duckduckgo # google, duckduckgo, bing, baidu, brave or custom
    layout:
      Infrastructure:
        style: columns
        columns: 3
      Management:
        style: columns
        columns: 2
      Automation:
        style: columns
        columns: 1
    providers:
      longhorn:
        url: https://longhorn.tail1c2108.ts.net

  widgets.yaml: |
    - openmeteo:
        label: Vienna # optional
        latitude: 48.2082
        longitude: 16.3738
        timezone: Europe/Vienna # optional
        units: metric # or imperial
        cache: 5 # Time in minutes to cache API responses, to stay within limits
        format: # optional, Intl.NumberFormat options
          maximumFractionDigits: 1
    # - search:
    #     provider: duckduckgo
    #     target: _blank
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          label: "K3s Cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - longhorn:
        # Show the expanded view
        expanded: true
        # Shows a node representing the aggregate values
        total: true
        # Shows the node names as labels
        labels: true
        # Show the nodes
        nodes: true

  services.yaml: |
    - Infrastructure:
        - Traefik:
            icon: traefik.png
            href: https://traefik.tyrongabriel.com
            description: Edge Router & Reverse Proxy
        - Longhorn:
            icon: longhorn.png
            href: https://longhorn.tail1c2108.ts.net/
            description: Distributed Block Storage
        - K8s Dashboard:
            icon: kubernetes.png
            href: https://kubernetes-dashboard.tail1c2108.ts.net/
            description: Cluster Management UI

    - Management:
        - Authentik:
            icon: authentik.png
            href: https://authentik.tyrongabriel.com
            description: Identity Provider
        - GitHub:
            icon: github-light.png
            href: https://github.com/
            description: Source Control

    - Automation:
        - n8n:
            icon: n8n.png
            href: https://n8n.tyrongabriel.com
            description: Workflow Automation

  bookmarks.yaml: |
    - Documentation:
        - Kubernetes:
            - abbr: K8s
              href: https://kubernetes.io/docs/
        - Homepage:
            - abbr: HP
              href: https://gethomepage.dev/
    - Social:
        - Reddit:
            - abbr: RD
              href: https://reddit.com/r/selfhosted

  custom.css: |
    .card-title {
      font-weight: 700;
      color: #38bdf8;
    }
    body {
      background-color: #0f172a;
    }

  docker.yaml: |
    ""
