apiVersion: ENC[AES256_GCM,data:7VM=,iv:IBSajpx7rEbULV3CWKUPitvzC92r797coffUyrfEdIc=,tag:sgFnrBvj1rvvw/Mbyqv7HQ==,type:str]
kind: ENC[AES256_GCM,data:mxG092e3,iv:JWkszljKOqwtLEVIFpO8lTiqtJrB3PHytTREDzFFj6s=,tag:TMXu0FFPSH8A/lDMIjRsIw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qnJOb7XQzlR/LHEDY48y,iv:KmU9J4sbiE0Gj0/XLAGZ9AgMMfGLBtFaKXExNkP19M0=,tag:uynBF7O1YGaeBDMkhnFtDg==,type:str]
    namespace: ENC[AES256_GCM,data:BZguQ49jeIU=,iv:pSBvWcnIWN4LzUUNiYTNMXnshcn/bIkiwdzJ/EyDJOE=,tag:wdqsCCrYPD28K9NVlyAhGw==,type:str]
type: ENC[AES256_GCM,data:M84O5yj3,iv:6G6CaoAx58qyzSWEcKxY7DPF0T5TnZl3W2W03RkcRaU=,tag:Vr1Uv1us6XbUCv57tl4zRA==,type:str]
#ENC[AES256_GCM,data:IjB180AgD3yHtPFozQHrDL3LU/CLjhBcweETyh5w+BUd8tHgllHLkLuIEAJRsMMbpd/hkxkZfWcaMyU=,iv:9IA9Wlna8lnSLtSL0G3+cywVR8Va71icsUCZRyr+TLM=,tag:oceZFoLcxidcXQWnq0uE1A==,type:comment]
stringData:
    HOMEPAGE_AUTHENTIK_API_KEY: ENC[AES256_GCM,data:Y+6fqQCNTHsbIf7+Z+aAo9ZjjmSuxRfOM2ZL8tPXF7Qly2MNG9ZfVtlai1TxQMFNW0m3gKp/MarGOvvT,iv:Yj0CKhx1razh2EugGclG+2V1V1BXrWbYwhV/2cwiN3c=,tag:UN5zhUgsMUQXmqvSVKILwQ==,type:str]
sops:
    age:
        - recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcjVHRTZNZjhMSTRKTHp4
            VTVOb2VQcDNFbmZtbmEySlQ3eUxvU2hCS3k0CmtrTWxIWFlJd1lYTTV3V2VCelQ3
            N1BrUGxycFdrZWpmNFBvKzRTYnQ2SXMKLS0tIDRPbEVCSUtqOFdjaHlUQlFmT1pr
            RmhZY3JyS00wZlFmRkZyanJSdUR5dWcK7J1yxxQFX9Ze0a7ULNMVAJAI8UfS9i11
            YYkH5nFhYJZbSBOdq0zFjztdlVGTkcbSXOqiJ21FLN37UBsTFiFIkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T15:00:37Z"
    mac: ENC[AES256_GCM,data:/lnqJLgoQq1XC6oypKmgGei0977r1OAULvZZQdHiUDCjhH0urHQBJ3KI5yeUdimxWB/dHY07xBIkSCsCRNL1rGr1WQgZteapM+bCUy/Gqr8fBsksF3P9XVJlakn0Tsa1Sl90bolpZiOD8OMMMnOyR2OtnyUqqVv4jU+DbifEpdg=,iv:ECPlTDcrmTdWO2VQwiVoXBaAFQ5INsBdBzIKRNRf30k=,tag:DaQ0s52HO6Hy2Ncj2bGToQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
