apiVersion: ENC[AES256_GCM,data:V64=,iv:O9sGsn6uny3fZ9xn7gRHQxlnM8c/q5NtHZ2Mp5+iC3w=,tag:hjnkJxTH6BerUFjCkABXOA==,type:str]
kind: ENC[AES256_GCM,data:PiAzL5YZ,iv:ESI2k+WWqrTjwhXfvSYBhO8aZ0Ik/9euWMqTelXbWYk=,tag:aXfnzamvfUed/Z1InJhn0g==,type:str]
type: ENC[AES256_GCM,data:6q6gHXK4,iv:xg8jt4ZbO4t1T9NfZiunSybDH1XtIPph8sjgE/uY4NI=,tag:VRBnjTUwIU74bGAekfeuAw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RLWRnMmc09uYY4I=,iv:VntFEOhfPcXLk6/0MppiNtxYLzpBTgXhOSHBZPVaJCs=,tag:0NN513bmCI/1dwUGjpYY0Q==,type:str]
    namespace: ENC[AES256_GCM,data:i+JG,iv:T6vV6AsLk6WNIxq0uyoMoQUrlAQpwL4gKJldRPBfKwU=,tag:vjz70wuzRrUPQFJ7yJ9YZg==,type:str]
    labels:
        app: ENC[AES256_GCM,data:KJko,iv:JxGuPcxnDY/f3QJIVjbXUK4ClcXwGVUjBIYolmpqgow=,tag:zJRYIsfLmHH9+Tbc26Pacw==,type:str]
        component: ENC[AES256_GCM,data:l24m7leaDQ==,iv:LctF9RcI639BJ9jzAN7HIvS7s1GjVIAl8Da/oyytVHM=,tag:EPktTi1LqcAqAtQbn866IA==,type:str]
stringData:
    #ENC[AES256_GCM,data:gmR5bYBP12J5l4OzrKKdU3a422UE6tM=,iv:I6KkGb3RHiFWeM+RqzSpUMdaAMq03Uo36RqLGhXmZ9Y=,tag:LYjE1HrLMDpVaxlC3wozjA==,type:comment]
    N8N_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:yX1X,iv:XCwO+WwYm6cBGoR8oo6bHPZG0B85hX/OrpMpAxwXAeA=,tag:9i+npJiHeLeGZauTKoPrkw==,type:str]
    #ENC[AES256_GCM,data:2jsov7XVx1hDJzpM2LqZtTm04MHimBHx60uBkPXQMJ4=,iv:0m6d7nHFFl2EGU5SkhVutsalk8V7WMEQPYRxLuZY3gQ=,tag:hYQCFTPDqpzZafHbXPoAxQ==,type:comment]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:x50LTMl/+A+e+V15i6uk/ERSqrOqy9b11OEN8BwrodItQJ2eKn2H22e3eHyVMXEjvhq0xvdF9tmGPVuItdjW2LXcpKAmTrFc1jZ/U2siyOQ=,iv:B7N7tuL/Mx42FKtuL1XYooHy+aGOaJvfM+8lKTdniGE=,tag:vj3DoVY98Zv2mkGY2b4q3w==,type:str]
sops:
    age:
        - recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q1FvNkx6UDh1b2Q3U3U1
            QVg5U1lGZlpFOGp0V0lzMmZ0UjRIRmNiQkRNCmU1T21XbkdXT29vYTdhOHVmWFJ4
            eGs2WUxZZVpZd09IVEoydVhabmhLbjAKLS0tIG9ZWEFsM2xzMDgwQTYrNG1lMElJ
            bFlxUWNJblFoQldoSllpL0JKYkttbGsKz6M2xoQj2Vcec5MxVPaDjIErL8sCmOMQ
            zQbzZSpbYgVuIJGCIpFHUdMvnEcZmkUERT0BKQc7arjYJolh5+YQAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T03:01:03Z"
    mac: ENC[AES256_GCM,data:eCC2IWJhz74ZIwutFbwQqDQBumzbFUDFzEwZqrJouQhELvqHod1Gk9cAR/45IKk3UT5PYkCUsR4rnsAG91V2piAtSsObhpAHPYUv06T1Hz3MmIxcvlcncyUVZbcOMJEndzeuXKxNFJ/lv9OFhPMK2BSs/lOM6V+CQM7OJ5n79/A=,iv:v/hMm+6D6U647HbGjEbuUUAslqh9PXe9yt/KH2u13bI=,tag:/wRksQaCqeIvjERQsOG1HQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
