oauth:
    clientId: ENC[AES256_GCM,data:+EUBLnspb0N1k4QqRkN9iRg=,iv:J54PZmLUzrOLfB+bkJuKDeVzrGeVqT1yxmwX5ut/GJo=,tag:In+TJUlgfuIPCxuHLojIfQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:YwE7rRNJYqfmUcU3Iv/BRbOSuK0Sr5VlGZ9eqOmXMuhulzyXV/r0ztDyZQnbDOhntFxJsUYedlG6jQrWnGzgGg==,iv:KN/3rsSIBIyV7Q0skxGpaARNDyfYQyDxUhzOTkvrEBg=,tag:m57S3239OynIebDfjLRK5A==,type:str]
sops:
    age:
        - recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aktsSDdjanlLbi85U3J2
            Y1ZoS1hKdGNac0ljVDdxejNIcWNYQklya0JrClpYbHl3U0NRSnBuRUZ0VUkyUktO
            NTZ3S0tMU3haRDVuSmRWVTlzenRGOTgKLS0tIHZjbGVycDhCOHlNZ2lCOE5GQ1Ev
            UDd3QitReGtORjhua0xCdWx5OXl5cXcKpE7GBkxps3ePhFcbcxzdogKWyJzP38O8
            ICR5JtyUBiWGxSmNmATROGCD5kkrYX5yveJVj2rR308GB1rO8s5AVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T23:37:05Z"
    mac: ENC[AES256_GCM,data:/z2pZd21AyHODZ4y9DA0AUW/F2rkNDsu4FHHJaepGVKL3/V+3Hf4odjqJj0KM6Pfhwe/7aegtKSDmyWNVaLZFEQheJ8tO1KnDBxUwO7PvxyzXgF+S874FniMKdgODg9dyx9mjRs7/D7cKMhNzV6stU54KU6PzxxbCrQrJlsKQyc=,iv:tDWAiQzxuZBTFqhhEuIdxHqRDSvYsgGZsJcRbPjKI8c=,tag:3uiVDE6zm7iZlS+eXjwUTw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
