trusted-proxies:
    - ENC[AES256_GCM,data:ZAp2rWDEh2VtEyHc,iv:eAHNN7sL4M/J+HBh3rgPckTfQzd6W8za40obCRkdiw8=,tag:HqgIeGq13O+XShOf+/D/WQ==,type:str]
cache-file: ENC[AES256_GCM,data:hQx8nwqOhPnP9SaWWmcWgqL25EdhnH3H,iv:JBKr6x+N+MY4xgepUu+t5SI5ItGu6xV0RTs4D2FsjX0=,tag:ylXQHD4l62DuRnsar0clKw==,type:str]
attachment-cache-dir: ENC[AES256_GCM,data:hGBkY7QU2+iOqcMwVfOd7DRjr1wIvaCTclZS,iv:ZtLiuc0IsEHpKcGHCsVtNYTyJA4a1rM3zcUXFpqb9+0=,tag:w/gAJ1fLAwQo+Et6qGk3IA==,type:str]
base-url: ENC[AES256_GCM,data:dfBVX9JuuDe1ZruVXgUbgHqCm5dLlEd5NUMMUSo=,iv:05CEzi9jYqeHZw+6PZwQts+HhjRc5qlC2hz6yjdlwZs=,tag:MkVoZGdrRdqCT/4P3XRgAw==,type:str]
behind-proxy: ENC[AES256_GCM,data:GO1rxA==,iv:mtIAdNvJ77TWb4JeCMbW95L0xFpTUDXMVcujB7e+iEw=,tag:OqqyyJbViPSb7IiHIWYexA==,type:bool]
attachment-total-size-limit: ENC[AES256_GCM,data:wYQ=,iv:+OAQFFodHcpKz2LYoxpRe/zI6ACpI8NPkgfMANaNKjc=,tag:KIyvuHMf4cRKOV0y7oQYxA==,type:str]
attachment-file-size-limit: ENC[AES256_GCM,data:1qbu,iv:9SXzJoYzAM0rEkZSFQC/q1mJ9tGAsO6GGPRnzLAH0IA=,tag:9kHrEYjPrSv5lh6uWKzRvg==,type:str]
attachment-expiry-duration: ENC[AES256_GCM,data:0OU=,iv:IE3UztyB3U0I8jWRoh2bYOmr3hJL13CG0iPQlAUjZv0=,tag:RktrrQU0SONupr7o8sZxZA==,type:str]
visitor-attachment-total-size-limit: ENC[AES256_GCM,data:4T1+QA==,iv:aVArXxs3yfOnd+T5iwqQCVjIJ82dNvkCC+0SvBE58Q4=,tag:qyyBlr1aOxZxuQEw5YmvoQ==,type:str]
visitor-attachment-daily-bandwidth-limit: ENC[AES256_GCM,data:F6szbw==,iv:cLCbe1weCbW3bQBD47mpcp732phusAQk0+SJ13kGhG4=,tag:kjLjvXzejcvbrLX7OMT9uw==,type:str]
auth-file: ENC[AES256_GCM,data:iCqdTt6CH8Aan+/vFZ/DRTQnJB0MTwE=,iv:xzRVOVcqnD3TElv291TzZ3XxwsjK5Kg1V8JcNL5xZLg=,tag:ufLXlKVfVYx0jMACE45LVA==,type:str]
auth-default-access: ENC[AES256_GCM,data:27aQPinDkL0=,iv:BdYOUALZ97WmVAhlxmpnX4i51UY64OhRMxu81yP8Cqk=,tag:/tH/yeoAnu+EgMry9WSS0A==,type:str]
auth-users:
    - ENC[AES256_GCM,data:RYvcfEt/Agu4ZWmj5qcI9GpaNql30hcoKiSGl95lpf+Vwgo+EOOlNQzfWELfN9iIoML5ODVKGr5bMuRf9ip5JcVK7lwzVT+L,iv:FA/ptq0RYkMLDPHDaxWb8xZ1C6Ft5sz3NO7pplpX4Fo=,tag:25jgFHiTNOR6vleOTif1JA==,type:str]
auth-tokens:
    - ENC[AES256_GCM,data:/NH53qxNfB7p6Y8RwK3cCL7ggbUGe12dTWROZsombxii2OKONqfrLhiV9T3+Lwc=,iv:/JFF4Ly28UYFcTd805MEydjV4NLLB2RHF8BA0vITOaM=,tag:eMKuxvMBW7+7pLEFZSL73Q==,type:str]
sops:
    age:
        - recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZEkzOFZuQVRzMHhvQ1pi
            YWhDL1N2OVRqZUhOYitFQjVPTks0MGc1aVIwCnQvMXR1Y2VmelR2aGFLY3ZZdDRt
            ZTI3NTFwbVdacjJJQ05lVVRqb285ZVkKLS0tIDlhbGhZQzVKWHF1ek1LbDJVSzYv
            MTc3ektENkxHUFRnUmxBM05QZTdBL0UKaPZfUJ7He44qoDrGAT5Uhhc80I4rMtQl
            LHBiY3fu0ZBLrge/oo2r2tGmuYLTXzhbNaKwBe8MwkT1YYC3CSgKfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T14:40:19Z"
    mac: ENC[AES256_GCM,data:H53fARMcyOl5P1o2oJspi2qlo7TLljRrxJdgUrqJFDdZxFoN7ieWjCqFq1sBFlPnkeBKwObiJ/EWamGRNOd8a4Oe/+bQ2cJF1jIOzzjwDbW4YsUwwrWABYJ94xRZsDbzPZSKR7V7aLYOpc15DIwwK9Jfc9TBG94FZSaFiH8p8yU=,iv:8vwQ8iPQEnweKKY0l98hETg6joQ6lzMhYKDZzQWkMOs=,tag:YH4p2fq1ClfCwmk0g5SKwg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
