apiVersion: ENC[AES256_GCM,data:rU0=,iv:NKjrD4zdQHTb0oOrg7jbIXWJlyLKBkS37V8mPZuaDrI=,tag:q3Xfw6t53r50u9k1JSmCPg==,type:str]
kind: ENC[AES256_GCM,data:ADq0T3R8,iv:b4JtDtwmNk4VPFWwHhEZaF0byQm1lc39fGw8pi63iVo=,tag:+breayBy5KescC6BQG+chA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/nCJBAYVjNrTj7gh+g==,iv:4TTesytuvyYLnOO2U2lFLpTaM4K8DdUuEueRCHRx9RQ=,tag:pZQJibgaNBIyXElLcxnAew==,type:str]
    namespace: ENC[AES256_GCM,data:a6etOWXkICCGINQUN8UO,iv:HcrRMDM7FZzezS9KxDJkxD/BKoULwMQPUYh+DcsgXy8=,tag:n7vUvn7O8H6JpqaO6yKFlA==,type:str]
type: ENC[AES256_GCM,data:nxpyIxD4,iv:ibvN/0nXDZQbu59+TUI8LuLi5Yt91MlDefX5sODZnF0=,tag:E4/zMoHrBhXlNGi19zTfiw==,type:str]
data:
    AWS_ENDPOINTS: ENC[AES256_GCM,data:xoaBhRCQLigebiDbue9grozGsWLyKuzP,iv:EsFuRERF5pF9nzLWIXb3OnCmUqZF5HEZ+bcBCd3gSAY=,tag:rQISYUSxVz5ZdnOI5Ryd0A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:jhhaOI5JtTkiulvzEETN33+Nfzpz,iv:OwFlQvmyHKjsEBFqxEEy1fdyXwGfJJ+LuvtnHDFfIOw=,tag:G9A1uKXl1dfB+bfEsocqUw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LTY8vzzKtImpbEaNIIjnqg7hoLELJXVWKQ==,iv:OQRDRkzjkbKK03u9kjYyLPDbRMEepc5/pWR+2XQHrHA=,tag:K+n4xD7+p0kQ3nyl/74ggw==,type:str]
sops:
    age:
        - recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNm1BdExFdXpyczlvUUtm
            Y2Z4NVkyTE5GU0ZkUVd0cjc1YThNSkFBNWpRCk0rUFFFbFljWmVMT3lzdlZNQnFM
            NnUyZU0xNFdGd3YrUi84QU1mQURudUUKLS0tIFRUd2JYZjVwRElaazh4MGNIVHRR
            SUlpQmJTT2lMYnV6QkdYN2E1MHdoT2MKRKtqacasu639CqSZWEJgbM2DqdEhukUr
            b02Gcr54QwvgKXICFFVswrspYWz7PMERpHBapg0g3gS4So30nqtZxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T11:45:13Z"
    mac: ENC[AES256_GCM,data:srNlu+dc4ln4eHkutfe0/T5GuaUqkTEIPw6hnIO9aYlEVokAAuwSyou3fPHzatV/zsO96MUWp6YqN2QcAv4pA7KlnbI4FuhSOySNsS38vC5dvFNEOHHtzqo9ivQm+eXdYWN1LDdPOgwbT++j/Zn55WBHykrdmAkxPsebIabcQVY=,iv:FuVmeEVEWvYhEmwQAckoPC9W4hfGFNG8YcXc8aMsDMw=,tag:uiwE9ZBDw0aGePfjGC2RFA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
